const ROLES = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  AUDITOR: 'AUDITOR',
  USER: 'USER',
  VIEWER: 'VIEWER'
};

const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_AUDIT: 'VIEW_AUDIT',
  SEARCH_AUDIT: 'SEARCH_AUDIT',
  IMPORT_AUDIT: 'IMPORT_AUDIT',
  EXPORT_AUDIT: 'EXPORT_AUDIT',
  MANAGE_COMPANIES: 'MANAGE_COMPANIES',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  PUBLISH_NOTICE: 'PUBLISH_NOTICE',
  VIEW_WHISTLEBLOWER: 'VIEW_WHISTLEBLOWER'
};

const ROLE_PERMISSIONS = {
  SYSTEM_ADMIN: Object.values(PERMISSIONS),

  COMPANY_ADMIN: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_AUDIT,
    PERMISSIONS.SEARCH_AUDIT,
    PERMISSIONS.IMPORT_AUDIT,
    PERMISSIONS.EXPORT_AUDIT,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.PUBLISH_NOTICE
  ],

  AUDITOR: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_AUDIT,
    PERMISSIONS.SEARCH_AUDIT,
    PERMISSIONS.EXPORT_AUDIT
  ],

  USER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_AUDIT
  ],

  VIEWER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_AUDIT
  ]
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS
};